AWSTemplateFormatVersion:
  "2010-09-09"
Description: "ALB"

# ------------------------------------------------------------#
# Input Parameters
# ------------------------------------------------------------#
Parameters:
  ProjectName:
    Type: String
    Default: bootapps-tmpl
  Stage:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prd
  AlbNameSuffix:
    Type: String
  AlbLogsS3BucketPrincipalAWSArn:
    Type: String
    Default: arn:aws:iam::582318560864:root
  S3BucketNameSuffix:
    Type: String
    Default: base

Resources:
  # ------------------------------------------------------------#
  #  ALB
  # ------------------------------------------------------------#
  ALB:
    Type: "AWS::ElasticLoadBalancingV2::LoadBalancer"
    DependsOn: LogBucketPolicyForALBLogs
    Properties:
      Name: !Sub "${ProjectName}-${Stage}-${AlbNameSuffix}"
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Stage}-${AlbNameSuffix}"
      # インターネット向け
      Scheme: "internet-facing"
      # 内部向け
#      Scheme: "internal"
      # ロードバランサーの属性
      LoadBalancerAttributes:
        # 削除保護が有効化されているかどうかを示します
        - Key: "deletion_protection.enabled"
          Value: false
          # アイドルタイムアウト値
        - Key: "idle_timeout.timeout_seconds"
          Value: 60
        - Key: "access_logs.s3.enabled"
          Value: true
        - Key: "access_logs.s3.bucket"
          Value: !Ref S3BucketForALBLogs
      SecurityGroups:
        - Fn::ImportValue:
            !Sub ${ProjectName}-${Stage}-sg-alb
      # 起動するサブネット
      Subnets:
        - Fn::ImportValue:
            !Sub ${ProjectName}-${Stage}-network-public1-subnet
        - Fn::ImportValue:
            !Sub ${ProjectName}-${Stage}-network-public2-subnet
        - Fn::ImportValue:
            !Sub ${ProjectName}-${Stage}-network-public3-subnet

  ALBListenerForProd:
    Type: "AWS::ElasticLoadBalancingV2::Listener"
    Properties:
      # デフォルトルールのアクション
      DefaultActions:
        - FixedResponseConfig:
            ContentType: text/plain
            MessageBody: "503 Error"
            StatusCode: 503
          Type: fixed-response
      LoadBalancerArn: !Ref ALB
      Port: 80
      Protocol: HTTP

  ALBListenerForTest:
    Type: "AWS::ElasticLoadBalancingV2::Listener"
    Properties:
      # デフォルトルールのアクション
      DefaultActions:
        - FixedResponseConfig:
            ContentType: text/plain
            MessageBody: "503 Error"
            StatusCode: 503
          Type: fixed-response
      LoadBalancerArn: !Ref ALB
      Port: 81
      Protocol: HTTP

  # ------------------------------------------------------------#
  #  S3Bucket for ALB logs
  # ------------------------------------------------------------#
  S3BucketForALBLogs:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Sub ${ProjectName}-${AlbNameSuffix}-logs-${S3BucketNameSuffix}-${Stage}
      AccessControl: Private
      VersioningConfiguration:
        Status: Suspended
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - BucketKeyEnabled: true
            ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
          - Id: !Sub ${ProjectName}-${AlbNameSuffix}-logs-lifecycle-rule-${Stage}
            Status: Enabled
            ExpirationInDays: 90
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${AlbNameSuffix}-logs-${Stage}
        - Key: ProjectName
          Value: !Ref ProjectName
        - Key: Stage
          Value: !Ref Stage

  LogBucketPolicyForALBLogs:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3BucketForALBLogs
      PolicyDocument:
        Statement:
          - Action:
              - s3:PutObject
            Effect: Allow
            Resource:
              - !Sub 'arn:aws:s3:::${ProjectName}-${AlbNameSuffix}-logs-${S3BucketNameSuffix}-${Stage}/*'
            Principal:
              AWS: !Ref AlbLogsS3BucketPrincipalAWSArn

# ------------------------------------------------------------#
# Output Parameters
# ------------------------------------------------------------#
Outputs:
  # ALB
  ALB:
    Value: !Ref ALB
    Export:
      Name: !Sub "${ProjectName}-${Stage}-${AlbNameSuffix}"

  # ALB Listener
  ALBListenerForProd:
    Value: !Ref ALBListenerForProd
    Export:
      Name: !Sub "${ProjectName}-${Stage}-${AlbNameSuffix}-listener-prod"
  ALBListenerForTest:
    Value: !Ref ALBListenerForTest
    Export:
      Name: !Sub "${ProjectName}-${Stage}-${AlbNameSuffix}-listener-test"
