AWSTemplateFormatVersion: '2010-09-09'
Description: 'ECS Service'
Parameters:
  ProjectName:
    Type: String
    Default: bootapps-tmpl

  EcsNameSuffix:
    Type: String
    Default: base


# + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +
Resources:
# + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +
# - - - - - - - - - - - - - - - - -
  ECSCluster:
# - - - - - - - - - - - - - - - - -
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Join
            - '-'
            - - !Ref ProjectName
              - cluster

# - - - - - - - - - - - - - - - - -
  ECSService:
# - - - - - - - - - - - - - - - - -
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref ECSCluster
      DeploymentController: CODE_DEPLOY
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 100
      DesiredCount: 0
      HealthCheckGracePeriodSeconds: 300
      LaunchType: FARGATE
      LoadBalancers:
        -
          TargetGroupArn:
            Fn::ImportValue:
              !Sub ${ProjectName}-alb-targetgroup-blue
          ContainerPort: 38080
          ContainerName: appserver
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups:
            - Fn::ImportValue:
                !Sub ${ProjectName}-sg-ecs
          Subnets:
            - Fn::ImportValue:
                !Sub ${ProjectName}-network-private1-subnet
            - Fn::ImportValue:
                !Sub ${ProjectName}-network-private2-subnet
            - Fn::ImportValue:
                !Sub ${ProjectName}-network-private3-subnet
      ServiceName: !Join
                      - '-'
                      - - !Ref ProjectName
                        - service
      TaskDefinition:
        Fn::ImportValue:
          !Join
            - '-'
            - - ECS
              - Task
              - !Ref ProjectName
              - !Ref EcsNameSuffix

# - - - - - - - - - - - - - - - - -
  ScalableTarget:
# - - - - - - - - - - - - - - - - -
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    DependsOn:
      - ECSService
    Properties:
      MaxCapacity: 10
      MinCapacity: 0
      ResourceId: !Join
          - /
          - - service
            - !Ref ECSCluster
            - !GetAtt ECSService.Name
      RoleARN: !Sub "arn:aws:iam::${AWS::AccountId}:role/aws-service-role/ecs.application-autoscaling.amazonaws.com/AWSServiceRoleForApplicationAutoScaling_ECSService"
      ScalableDimension: ecs:service:DesiredCount
      ServiceNamespace: ecs

# - - - - - - - - - - - - - - - - -
  ScalingPolicyCPU:
# - - - - - - - - - - - - - - - - -
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    DependsOn:
      - ScalableTarget
    Properties:
      ScalingTargetId: !Ref ScalableTarget
      ServiceNamespace: ecs
      PolicyName: !Join
                  - '-'
                  - - !Ref ProjectName
                    - ECS
                    - CPU
                    - ScalePolicy
      PolicyType: TargetTrackingScaling
      ScalableDimension: ecs:service:DesiredCount
      TargetTrackingScalingPolicyConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: ECSServiceAverageCPUUtilization
        TargetValue: 70.0
        ScaleOutCooldown: 180
        ScaleInCooldown: 60
        DisableScaleIn: false   # スケールインする

# - - - - - - - - - - - - - - - - -
  ScalingPolicyMemory:
# - - - - - - - - - - - - - - - - -
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    DependsOn:
      - ScalableTarget
    Properties:
      ScalingTargetId: !Ref ScalableTarget
      ServiceNamespace: ecs
      PolicyName: !Join
                  - '-'
                  - - !Ref ProjectName
                    - ECS
                    - Memory
                    - ScalePolicy
      PolicyType: TargetTrackingScaling
      ScalableDimension: ecs:service:DesiredCount
      TargetTrackingScalingPolicyConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: ECSServiceAverageMemoryUtilization
        TargetValue: 80.0
        ScaleOutCooldown: 300
        ScaleInCooldown: 300
        DisableScaleIn: false   # スケールインする

# - - - - - - - - - - - - - - - - -
  CPUAlarmHigh:
# - - - - - - - - - - - - - - - - -
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmName: !Join
                  - ' '
                  - - "ECS CPU Utilization > 70% for 3 minutes"
                    - !GetAtt ECSService.Name
      AlarmDescription: !Ref ECSService
      MetricName: CPUUtilization
      Namespace: AWS/ECS
      Statistic: Average
      Period: 60
      EvaluationPeriods: 3
      ComparisonOperator: GreaterThanThreshold
      Threshold: 70
      TreatMissingData: missing
      Dimensions:
        - Name: ServiceName
          Value: !GetAtt ECSService.Name
        - Name: ClusterName
          Value: !Ref ECSCluster


# - - - - - - - - - - - - - - - - -
  MemoryAlarmHigh:
# - - - - - - - - - - - - - - - - -
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmName: !Join
                  - ' '
                  - - "ECS Memory Utilization > 80% for 3 minutes"
                    - !GetAtt ECSService.Name
      AlarmDescription: !Ref ECSService
      MetricName: MemoryUtilization
      Namespace: AWS/ECS
      Statistic: Maximum
      Period: 60
      EvaluationPeriods: 3
      ComparisonOperator: GreaterThanThreshold
      Threshold: 80
      TreatMissingData: missing
      Dimensions:
        - Name: ServiceName
          Value: !GetAtt ECSService.Name
        - Name: ClusterName
          Value: !Ref ECSCluster


# + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +
Outputs:
# + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +
  # - - - - - - - - - - - - - - - - -
  ECSCluster:
    Value: !Ref ECSCluster
    Export:
      Name: !Join
        - '-'
        - - ECS
          - Cluster
          - !Ref ProjectName

  # - - - - - - - - - - - - - - - - -
  ECSService:
    Value: !Ref ECSService
    Export:
      Name: !Join
        - '-'
        - - ECS
          - Service
          - !Ref ProjectName
