AWSTemplateFormatVersion: '2010-09-09'
Description: 'ECS Service'

Parameters:
  ProjectName:
    Type: String
    Default: bootapps-tmpl
  ApplicationName:
    Type: String
    Default: webapp-example
  Stage:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prd

## + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +
#Mappings:
#  # + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +
#  scaling:
#    dev:
#      MinCapacity: 1
#      MaxCapacity: 2
#
#    prod:
#      MinCapacity: 2
#      MaxCapacity: 5

# + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +
Resources:
# + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +

# - - - - - - - - - - - - - - - - -
  ECSService:
# - - - - - - - - - - - - - - - - -
    Type: AWS::ECS::Service
    Properties:
      Cluster:
        Fn::ImportValue:
          !Sub ECS-Cluster-${ProjectName}-${Stage}
      DeploymentController:
        Type: CODE_DEPLOY
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 100
      DesiredCount: 0
      EnableExecuteCommand: true
      HealthCheckGracePeriodSeconds: 300
      LaunchType: FARGATE
      LoadBalancers:
        -
          TargetGroupArn:
            Fn::ImportValue:
              !Sub ${ApplicationName}-${Stage}-tg-blue-arn
          ContainerPort: 38080
          ContainerName: !Ref ApplicationName
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED # Publicサブネットで動かす場合はパブリックIPを割り当てないとインターネットに出られない
          SecurityGroups:
            - Fn::ImportValue:
                !Sub ${ProjectName}-${Stage}-sg-ecs
          Subnets:
            - Fn::ImportValue:
                !Sub ${ProjectName}-${Stage}-network-public1-subnet
            - Fn::ImportValue:
                !Sub ${ProjectName}-${Stage}-network-public2-subnet
            - Fn::ImportValue:
                !Sub ${ProjectName}-${Stage}-network-public3-subnet
      ServiceName: !Join
                      - '-'
                      - - !Ref ProjectName
                        - !Ref Stage
                        - !Ref ApplicationName
                        - service
      TaskDefinition:
        Fn::ImportValue:
          !Join
            - '-'
            - - ECS
              - Task
              - !Ref ProjectName
              - !Ref Stage
              - !Ref ApplicationName
#
## - - - - - - - - - - - - - - - - -
#  ScalableTarget:
## - - - - - - - - - - - - - - - - -
#    Type: AWS::ApplicationAutoScaling::ScalableTarget
#    DependsOn:
#      - ECSService
#    Properties:
#      MaxCapacity: !FindInMap [ scaling, !Ref Stage, MaxCapacity ]
#      MinCapacity: !FindInMap [ scaling, !Ref Stage, MinCapacity ]
#      ResourceId: !Join
#          - /
#          - - service
#            - !Ref ECSCluster
#            - !GetAtt ECSService.Name
#      RoleARN: !Sub "arn:aws:iam::${AWS::AccountId}:role/aws-service-role/ecs.application-autoscaling.amazonaws.com/AWSServiceRoleForApplicationAutoScaling_ECSService"
#      ScalableDimension: ecs:service:DesiredCount
#      ServiceNamespace: ecs
#
## - - - - - - - - - - - - - - - - -
#  ScalingPolicyCPU:
## - - - - - - - - - - - - - - - - -
#    Type: AWS::ApplicationAutoScaling::ScalingPolicy
#    DependsOn:
#      - ScalableTarget
#    Properties:
#      ScalingTargetId: !Ref ScalableTarget
#      ServiceNamespace: ecs
#      PolicyName: !Join
#                  - '-'
#                  - - !Ref ProjectName
#                    - ECS
#                    - CPU
#                    - ScalePolicy
#      PolicyType: TargetTrackingScaling
#      ScalableDimension: ecs:service:DesiredCount
#      TargetTrackingScalingPolicyConfiguration:
#        PredefinedMetricSpecification:
#          PredefinedMetricType: ECSServiceAverageCPUUtilization
#        TargetValue: 70.0
#        ScaleOutCooldown: 180
#        ScaleInCooldown: 60
#        DisableScaleIn: false   # スケールインする
#
## - - - - - - - - - - - - - - - - -
#  ScalingPolicyMemory:
## - - - - - - - - - - - - - - - - -
#    Type: AWS::ApplicationAutoScaling::ScalingPolicy
#    DependsOn:
#      - ScalableTarget
#    Properties:
#      ScalingTargetId: !Ref ScalableTarget
#      ServiceNamespace: ecs
#      PolicyName: !Join
#                  - '-'
#                  - - !Ref ProjectName
#                    - ECS
#                    - Memory
#                    - ScalePolicy
#      PolicyType: TargetTrackingScaling
#      ScalableDimension: ecs:service:DesiredCount
#      TargetTrackingScalingPolicyConfiguration:
#        PredefinedMetricSpecification:
#          PredefinedMetricType: ECSServiceAverageMemoryUtilization
#        TargetValue: 80.0
#        ScaleOutCooldown: 300
#        ScaleInCooldown: 300
#        DisableScaleIn: false   # スケールインする
#
## - - - - - - - - - - - - - - - - -
#  CPUAlarmHigh:
## - - - - - - - - - - - - - - - - -
#    Type: AWS::CloudWatch::Alarm
#    Properties:
#      ActionsEnabled: true
#      AlarmName: !Join
#                  - ' '
#                  - - "ECS CPU Utilization > 70% for 3 minutes"
#                    - !GetAtt ECSService.Name
#      AlarmDescription: !Ref ECSService
#      MetricName: CPUUtilization
#      Namespace: AWS/ECS
#      Statistic: Average
#      Period: 60
#      EvaluationPeriods: 3
#      ComparisonOperator: GreaterThanThreshold
#      Threshold: 70
#      TreatMissingData: missing
#      Dimensions:
#        - Name: ServiceName
#          Value: !GetAtt ECSService.Name
#        - Name: ClusterName
#          Value: !Ref ECSCluster
#
#
## - - - - - - - - - - - - - - - - -
#  MemoryAlarmHigh:
## - - - - - - - - - - - - - - - - -
#    Type: AWS::CloudWatch::Alarm
#    Properties:
#      ActionsEnabled: true
#      AlarmName: !Join
#                  - ' '
#                  - - "ECS Memory Utilization > 80% for 3 minutes"
#                    - !GetAtt ECSService.Name
#      AlarmDescription: !Ref ECSService
#      MetricName: MemoryUtilization
#      Namespace: AWS/ECS
#      Statistic: Maximum
#      Period: 60
#      EvaluationPeriods: 3
#      ComparisonOperator: GreaterThanThreshold
#      Threshold: 80
#      TreatMissingData: missing
#      Dimensions:
#        - Name: ServiceName
#          Value: !GetAtt ECSService.Name
#        - Name: ClusterName
#          Value: !Ref ECSCluster


# + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +
Outputs:
# + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +
  # - - - - - - - - - - - - - - - - -
  ECSServiceArn:
    Value: !Ref ECSService
    Export:
      Name: !Join
        - '-'
        - - ECS
          - ServiceArn
          - !Ref ProjectName
          - !Ref Stage
  ECSServiceName:
    Value: !GetAtt ECSService.Name
    Export:
      Name: !Join
        - '-'
        - - ECS
          - ServiceName
          - !Ref ProjectName
          - !Ref Stage


