AWSTemplateFormatVersion: '2010-09-09'
Description: 'ECS Task Definition'
Parameters:
  ProjectName:
    Type: String
    Default: bootapps-tmpl

  EcsNameSuffix:
    Type: String
    Default: base

  Stage:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - stg
      - prd

# + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +
Mappings:
# + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +
  spec:
    dev:
      CPU: 1024
      Memory: 2GB

# + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +
Resources:
# + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +

# - - - - - - - - - - - - - - - - -
  ECSTask:
# - - - - - - - - - - - - - - - - -
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        -
          Name: !Sub ${ProjectName}-base
          Image: !Sub
            - ${AwsAccountId}.dkr.ecr.ap-northeast-1.amazonaws.com/${ProjectName}/application:latest
            - AwsAccountId:
                !Ref AWS::AccountId
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group:
                Fn::ImportValue:
                  !Sub ECS-LogGroup-${ProjectName}
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: !Ref Stage
          # MemoryReservation: 2048
          PortMappings:
            -
              HostPort: 38080
              Protocol: tcp
              ContainerPort: 38080

      ExecutionRoleArn:
        Fn::ImportValue:
          !Sub ECS-ExecRoleArn-${ProjectName}
      Family: !Sub '${ProjectName}-${EcsNameSuffix}'
      NetworkMode: awsvpc
      Cpu: !FindInMap [ spec, !Ref Stage, CPU ]
      Memory: !FindInMap [ spec, !Ref Stage, Memory ]
      RequiresCompatibilities:
        - FARGATE

# + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +
Outputs:
# + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +
# - - - - - - - - - - - - - - - - -
  ECSTask:
    Value: !Ref ECSTask
    Export:
      Name: !Join
            - '-'
            - - ECS
              - Task
              - !Ref ProjectName
              - !Ref EcsNameSuffix
