AWSTemplateFormatVersion: '2010-09-09'
Description: 'ECS Role, LogGroup'
Parameters:
  ProjectName:
    Type: String
    Default: bootapps-tmpl

# + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +
Resources:
# + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/ecs/${ProjectName}'
      RetentionInDays: 365

  TaskExecRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join
              - '-'
              - - !Ref ProjectName
                - ECS
                - ExecRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          -
            Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      Policies:
        - PolicyName: SecretManager
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - secretsmanager:GetSecretValue
                Effect: Allow
                Resource: '*'
        - PolicyName: SystemsManagerGetParameter
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - ssm:GetParameters
                  - ssm:GetParameter
                Effect: Allow
                Resource: '*'

  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join
        - '-'
        - - !Ref ProjectName
          - ECS
          - TaskRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          -
            Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy


# + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +
Outputs:
# + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +
# - - - - - - - - - - - - - - - - -
  LogGroup:
    Value: !Ref LogGroup
    Export:
      Name: !Join
        - '-'
        - - ECS
          - LogGroup
          - !Ref ProjectName

# - - - - - - - - - - - - - - - - -
  TaskExecRole:
    Value: !Ref TaskExecRole
    Export:
      Name: !Join
            - '-'
            - - ECS
              - ExecRole
              - !Ref ProjectName

# - - - - - - - - - - - - - - - - -
  TaskExecRoleArn:
    Value: !GetAtt TaskExecRole.Arn
    Export:
      Name: !Join
            - '-'
            - - ECS
              - ExecRoleArn
              - !Ref ProjectName

  # - - - - - - - - - - - - - - - - -
  TaskRole:
    Value: !Ref TaskRole
    Export:
      Name: !Join
        - '-'
        - - ECS
          - TaskRole
          - !Ref ProjectName

  # - - - - - - - - - - - - - - - - -
  TaskRoleArn:
    Value: !GetAtt TaskRole.Arn
    Export:
      Name: !Join
        - '-'
        - - ECS
          - TaskRoleArn
          - !Ref ProjectName
