AWSTemplateFormatVersion: '2010-09-09'
Description: 'CI CodeDeploy.'

Parameters:
  ProjectName:
    Type: String
    Default: bootapps-tmpl
  TerminationWaitTimeInMinutes:
    Type: Number
    Default: 0
  Stage:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prd
  ApplicationName:
    Type: String
    Default: webapp-example
  AlbNameSuffix:
    Type: String

# + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +
Resources:
# + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +
  Application:
    Type: "AWS::CodeDeploy::Application"
    Properties:
      ApplicationName: !Sub DeployApp-${ProjectName}-${Stage}-${ApplicationName}
      ComputePlatform: ECS

  DeploymentGroup:
    Type: AWS::CodeDeploy::DeploymentGroup
    Properties:
      ApplicationName: !Ref Application
      DeploymentGroupName: !Sub DeploymentGroup-${ProjectName}-${Stage}-${ApplicationName}
      DeploymentStyle:
        DeploymentType: BLUE_GREEN
        DeploymentOption: WITH_TRAFFIC_CONTROL
      BlueGreenDeploymentConfiguration:
        DeploymentReadyOption:
          ActionOnTimeout: CONTINUE_DEPLOYMENT
#          ActionOnTimeout: STOP_DEPLOYMENT
#          WaitTimeInMinutes: 1440
        TerminateBlueInstancesOnDeploymentSuccess:
          Action: TERMINATE
          TerminationWaitTimeInMinutes: !Ref TerminationWaitTimeInMinutes
      DeploymentConfigName: CodeDeployDefault.ECSAllAtOnce
      LoadBalancerInfo:
        TargetGroupPairInfoList:
          - TargetGroups:
            - Name:
                Fn::ImportValue: !Sub ${ApplicationName}-${Stage}-tg-blue
            - Name:
                Fn::ImportValue: !Sub ${ApplicationName}-${Stage}-tg-green
            ProdTrafficRoute:
              ListenerArns:
                - Fn::ImportValue: !Sub ${ProjectName}-${Stage}-${AlbNameSuffix}-listener-prod
            TestTrafficRoute:
              ListenerArns:
                - Fn::ImportValue: !Sub ${ProjectName}-${Stage}-${AlbNameSuffix}-listener-test
      ECSServices:
        - ClusterName:
            Fn::ImportValue: !Sub ECS-Cluster-${ProjectName}-${Stage}
          ServiceName:
            Fn::ImportValue: !Sub ECS-ServiceName-${ProjectName}-${Stage}
      ServiceRoleArn:
        Fn::ImportValue: !Sub CodeDeployRoleArn-${ProjectName}-${Stage}

# + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +
Outputs:
# + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +
  # - - - - - - - - - - - - - - - - -
  DeploymentGroup:
    Value: !Ref DeploymentGroup
    Export:
      Name: !Join
        - '-'
        - - DeploymentGroup
          - !Sub ${ProjectName}
          - !Sub ${Stage}
