AWSTemplateFormatVersion: '2010-09-09'
Description: 'CI Base Resources'
Parameters:
  ProjectName:
    Type: String
    Default: bootapps-tmpl
  Stage:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prd
  S3BucketNameSuffix:
    Type: String
    Default: ""

Conditions:
  UseDefaultAccountId: !Equals [!Ref S3BucketNameSuffix, ""]

# + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +
Resources:
# + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +
# - - - - - - - - - - - - - - - - -
  S3BucketResources:
# - - - - - - - - - - - - - - - - -
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Join
            - '-'
            - - !Ref ProjectName
              - !Ref Stage
              - resources
              - !If
                - UseDefaultAccountId
                - !Ref "AWS::AccountId"
                - !Ref S3BucketNameSuffix
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Suspended
      LifecycleConfiguration:
        Rules:
          - Id: PurgeOutdatedArtifacts
            Status: Enabled
            ExpirationInDays: 30
      Tags:
        - Key: Name
          Value: !Join
            - '-'
            - - !Ref ProjectName
              - !Ref Stage
              - resources
              - !If
                - UseDefaultAccountId
                - !Ref "AWS::AccountId"
                - !Ref S3BucketNameSuffix
        - Key: ProjectName
          Value: !Ref ProjectName
        - Key: Stage
          Value: !Ref Stage

## - - - - - - - - - - - - - - - - -
  CodebuildRole:
# - - - - - - - - - - - - - - - - -
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join
        - '-'
        - - !Ref ProjectName
          - !Ref Stage
          - CodeBuild
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
        Version: '2012-10-17'
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryPowerUser
      Policies:
        - PolicyName: CloudWatchLogs
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Effect: Allow
                Resource:
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild*

        - PolicyName: S3Artifacts
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - s3:PutObject
                  - s3:PutObjectAcl
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:GetBucketVersioning
                Effect: Allow
                Resource:
                  - !Join
                    - '/'
                    - - !GetAtt S3BucketResources.Arn
                      - '*'
                  - !Join
                    - '/'
                    - - Fn::ImportValue:
                          !Sub S3BucketArn-${ProjectName}-${Stage}-ecs-extras
                      - '*'
        - PolicyName: VPCPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - ec2:CreateNetworkInterface
                  - ec2:DescribeDhcpOptions
                  - ec2:DescribeNetworkInterfaces
                  - ec2:DeleteNetworkInterface
                  - ec2:DescribeSubnets
                  - ec2:DescribeSecurityGroups
                  - ec2:DescribeVpcs
                Effect: Allow
                Resource: '*'
              - Action:
                  - ec2:CreateNetworkInterfacePermission
                Effect: Allow
                Resource: !Sub arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:network-interface/*
                Condition:
                  StringEquals:
                    ec2:Subnet:
                      - !Join
                        - '/'
                        - - !Sub arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:subnet
                          - Fn::ImportValue:
                              !Sub ${ProjectName}-${Stage}-network-public1-subnet
                      - !Join
                        - '/'
                        - - !Sub arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:subnet
                          - Fn::ImportValue:
                              !Sub ${ProjectName}-${Stage}-network-public2-subnet
                      - !Join
                        - '/'
                        - - !Sub arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:subnet
                          - Fn::ImportValue:
                              !Sub ${ProjectName}-${Stage}-network-public3-subnet
                      - !Join
                        - '/'
                        - - !Sub arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:subnet
                          - Fn::ImportValue:
                              !Sub ${ProjectName}-${Stage}-network-public1-subnet
                      - !Join
                        - '/'
                        - - !Sub arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:subnet
                          - Fn::ImportValue:
                              !Sub ${ProjectName}-${Stage}-network-public2-subnet
                      - !Join
                        - '/'
                        - - !Sub arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:subnet
                          - Fn::ImportValue:
                              !Sub ${ProjectName}-${Stage}-network-public3-subnet

        - PolicyName: SecretManager
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - secretsmanager:GetSecretValue
                Effect: Allow
                Resource: '*'
        - PolicyName: SystemsManagerGetParameter
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - ssm:GetParameters
                  - ssm:GetParameter
                Effect: Allow
                Resource: '*'
        - PolicyName: EcrBuildDeploy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - ecr:PutImageTagMutability
                  - ecr:StartImageScan
                  - ecr:DescribeImageReplicationStatus
                  - ecr:ListTagsForResource
                  - ecr:UploadLayerPart
                  - ecr:BatchDeleteImage
                  - ecr:ListImages
                  - ecr:BatchGetRepositoryScanningConfiguration
                  - ecr:DeleteRepository
                  - ecr:CompleteLayerUpload
                  - ecr:TagResource
                  - ecr:DescribeRepositories
                  - ecr:BatchCheckLayerAvailability
                  - ecr:ReplicateImage
                  - ecr:GetLifecyclePolicy
                  - ecr:PutLifecyclePolicy
                  - ecr:DescribeImageScanFindings
                  - ecr:GetLifecyclePolicyPreview
                  - ecr:CreateRepository
                  - ecr:PutImageScanningConfiguration
                  - ecr:GetDownloadUrlForLayer
                  - ecr:DeleteLifecyclePolicy
                  - ecr:PutImage
                  - ecr:UntagResource
                  - ecr:BatchGetImage
                  - ecr:DescribeImages
                  - ecr:StartLifecyclePolicyPreview
                  - ecr:InitiateLayerUpload
                  - ecr:GetRepositoryPolicy
                Effect: Allow
                Resource: !Sub arn:aws:ecr:*:${AWS::AccountId}:${ProjectName}/${Stage}/*

        - PolicyName: EcsDeploy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - ecs:DescribeServices
                  - ecs:CreateTaskSet
                  - ecs:UpdateService
                  - ecs:UpdateServicePrimaryTaskSet
                  - ecs:RegisterTaskDefinition
                  - ecs:DeleteTaskSet
                Effect: Allow
                Resource: '*'
              - Action:
                  - iam:PassRole
                Condition:
                  StringLike:
                    'iam:PassedToService': 'ecs-tasks.amazonaws.com'
                Effect: Allow
                Resource: '*'

# - - - - - - - - - - - - - - - - -
  CodePipelineRole:
# - - - - - - - - - - - - - - - - -
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join
        - '-'
        - - !Ref ProjectName
          - !Ref Stage
          - CodePipeline
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - codepipeline.amazonaws.com
        Version: '2012-10-17'
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
        - arn:aws:iam::aws:policy/AWSCodePipelineApproverAccess
        - arn:aws:iam::aws:policy/AWSCodeBuildDeveloperAccess
        - arn:aws:iam::aws:policy/AmazonECS_FullAccess
      Policies:
        - PolicyName: CodePipelineArtifactsPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - s3:PutObject
                  - s3:PutObjectAcl
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:GetBucketVersioning
                Effect: Allow
                Resource: !Join
                  - '/'
                  - - !GetAtt S3BucketResources.Arn
                    - '*'
        - PolicyName: InterfaceWithCodeCommit
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - codecommit:CancelUploadArchive
                  - codecommit:GetBranch
                  - codecommit:GetCommit
                  - codecommit:GetUploadArchiveStatus
                  - codecommit:UploadArchive
                Effect: Allow
                Resource: '*'
        - PolicyName: SystemsManagerGetParameter
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - ssm:GetParameters
                  - ssm:GetParameter
                Effect: Allow
                Resource: '*'
        - PolicyName: UseCodeStarConnections
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - codestar-connections:UseConnection
                  - codestar-connections:GetConnection
                  - codestar-connections:ListConnections
                Effect: Allow
                Resource: '*'

  # - - - - - - - - - - - - - - - - -
  CodeDeployRole:
    # - - - - - - - - - - - - - - - - -
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join
        - '-'
        - - !Ref ProjectName
          - !Ref Stage
          - CodeDeploy
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - codedeploy.amazonaws.com
        Version: '2012-10-17'
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCodeDeployRoleForECS
      Policies:
        - PolicyName: SystemsManagerGetParameter
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - ssm:GetParameters
                  - ssm:GetParameter
                Effect: Allow
                Resource: '*'

  CodeBuildLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/codebuild'
      RetentionInDays: 5

# + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +
Outputs:
# + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +
# - - - - - - - - - - - - - - - - -
  S3BucketResources:
    Value: !Ref S3BucketResources
    Export:
      Name: !Join
        - '-'
        - - S3Bucket
          - !Ref ProjectName
          - !Ref Stage
          - resources
  S3BucketResourcesArn:
    Value: !GetAtt S3BucketResources.Arn
    Export:
      Name: !Join
        - '-'
        - - S3BucketArn
          - !Ref ProjectName
          - !Ref Stage
          - resources

  # - - - - - - - - - - - - - - - - -
  CodebuildRole:
    Value: !Ref CodebuildRole
    Export:
      Name: !Join
        - '-'
        - - CodebuildRole
          - !Ref ProjectName
          - !Ref Stage

  CodebuildRoleArn:
    Value: !GetAtt CodebuildRole.Arn
    Export:
      Name: !Join
        - '-'
        - - CodebuildRoleArn
          - !Ref ProjectName
          - !Ref Stage

  # - - - - - - - - - - - - - - - - -
  CodePipelineRole:
    Value: !Ref CodePipelineRole
    Export:
      Name: !Join
        - '-'
        - - CodePipelineRole
          - !Ref ProjectName
          - !Ref Stage

  CodePipelineRoleArn:
    Value: !GetAtt CodePipelineRole.Arn
    Export:
      Name: !Join
        - '-'
        - - CodePipelineRoleArn
          - !Ref ProjectName
          - !Ref Stage

  # - - - - - - - - - - - - - - - - -
  CodeDeployRole:
    Value: !Ref CodeDeployRole
    Export:
      Name: !Join
        - '-'
        - - CodeDeployRole
          - !Ref ProjectName
          - !Ref Stage

  CodeDeployRoleArn:
    Value: !GetAtt CodeDeployRole.Arn
    Export:
      Name: !Join
        - '-'
        - - CodeDeployRoleArn
          - !Ref ProjectName
          - !Ref Stage

  CodeBuildLogGroup:
    Description: "LogGroup for CodeBuild"
    Value: !Ref CodeBuildLogGroup
    Export:
      Name: !Join
        - '-'
        - - CodeBuild
          - LogGroup
          - !Ref ProjectName
          - !Ref Stage