AWSTemplateFormatVersion: '2010-09-09'
Description: 'CI CodePipeline.'

Parameters:
  ProjectName:
    Type: String
    Default: bootapps-tmpl
  Stage:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prd
  GithubOrganization:
    Type: String
    Default: value-it
  GithubRepository:
    Type: String
    Default: springboot-apps-template
  CodeStarConnectionArn:
    Type: String
  ApplicationName:
    Type: String
    Default: webapp-example

# + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +
Mappings:
  # + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +
  source:
    dev:
      branch: master
    prod:
      branch: master


# + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +
Resources:
# + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +

# - - - - - - - - - - - - - - - - -
  CodePipeline:
# - - - - - - - - - - - - - - - - -
    Type: AWS::CodePipeline::Pipeline
    Properties:
      ArtifactStore:
        Type: S3
        Location:
            Fn::ImportValue:
              !Sub S3Bucket-${ProjectName}-${Stage}-resources
      Name: !Join
              - '-'
              - - !Ref ProjectName
                - !Ref Stage
                - !Ref ApplicationName
                - pipeline
      RoleArn:
        Fn::ImportValue:
          !Sub CodePipelineRoleArn-${ProjectName}-${Stage}
      Stages:
        -
          Name: SourceStage
          Actions:
            -
              Name: SourcePull
              ActionTypeId:
                Category: Source
                Owner: AWS
                Version: 1
                Provider: CodeStarSourceConnection
              OutputArtifacts:
                -
                  Name: SourceArtifact
              Configuration:
                FullRepositoryId: !Sub "${GithubOrganization}/${GithubRepository}"
                ConnectionArn: !Ref CodeStarConnectionArn
                BranchName: !FindInMap [ source, !Ref Stage, branch ]
                DetectChanges: "false"
              RunOrder: 1

        -
          Name: BuildStage
          Actions:
            -
              Name: BuildApplication
              InputArtifacts:
                -
                  Name: SourceArtifact
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              Configuration:
                ProjectName:
                  Fn::ImportValue:
                    !Join
                      - '-'
                      - - CodeBuild
                        - !Ref ProjectName
                        - !Ref Stage
                        - !Ref ApplicationName
              OutputArtifacts:
                -
                  Name: BuildArtifact
              RunOrder: 1

#        -
#          Name: ApprovalStage
#          Actions:
#            -
#              Name: ApprovalBeforeDeploy
#              ActionTypeId:
#                Category: Approval
#                Owner: AWS
#                Version: 1
#                Provider: Manual

        -
          Name: DeployStage
          Actions:
            -
              Name: DeployToECS
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: 1
                Provider: CodeDeployToECS
              InputArtifacts:
                - Name: BuildArtifact
              Configuration:
                AppSpecTemplateArtifact: BuildArtifact
                AppSpecTemplatePath: appspec.yaml
                TaskDefinitionTemplateArtifact: BuildArtifact
                TaskDefinitionTemplatePath: taskdef.json
                ApplicationName: !Sub DeployApp-${ProjectName}-${Stage}-${ApplicationName}
                DeploymentGroupName: !Sub DeploymentGroup-${ProjectName}-${Stage}-${ApplicationName}
                Image1ArtifactName: BuildArtifact
                Image1ContainerName: IMAGE1_NAME
