AWSTemplateFormatVersion: '2010-09-09'
Description: 'ECS Role, LogGroup'
Parameters:
  ProjectName:
    Type: String
    Default: bootapps-tmpl
  CreateServiceLinkedRole:
    Type: String
    Default: "true"
    AllowedValues:
      - "true"
      - "false"
  Stage:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prd
  S3BucketNameSuffix:
    Type: String
    Default: ""

Conditions:
  ShouldCreateServiceLinkedRole: !Equals [!Ref CreateServiceLinkedRole, "true"]
  UseDefaultAccountId: !Equals [!Ref S3BucketNameSuffix, ""]

# + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +
Resources:
# + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/ecs/${ProjectName}/${Stage}'
      RetentionInDays: 365

  TaskExecRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join
              - '-'
              - - !Ref ProjectName
                - !Ref Stage
                - ECS
                - ExecRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          -
            Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      Policies:
        - PolicyName: SecretManager
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - secretsmanager:GetSecretValue
                Effect: Allow
                Resource: '*'
        - PolicyName: SystemsManagerGetParameter
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - ssm:GetParameters
                  - ssm:GetParameter
                Effect: Allow
                Resource: '*'

  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join
        - '-'
        - - !Ref ProjectName
          - !Ref Stage
          - ECS
          - TaskRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          -
            Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AWSXrayFullAccess

  AWSServiceLinkedRole:
    Type: AWS::IAM::ServiceLinkedRole
    Condition: ShouldCreateServiceLinkedRole
    Properties:
      AWSServiceName: ecs.amazonaws.com

  # - - - - - - - - - - - - - - - - -
  S3BucketEcsExtras:
    # - - - - - - - - - - - - - - - - -
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Join
        - '-'
        - - !Ref ProjectName
          - !Ref Stage
          - ecs
          - extras
          - !If
            - UseDefaultAccountId
            - !Ref "AWS::AccountId"
            - !Ref S3BucketNameSuffix
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Suspended
      Tags:
        - Key: Name
          Value: !Join
            - '-'
            - - !Ref ProjectName
              - !Ref Stage
              - ecs
              - extras
              - !If
                - UseDefaultAccountId
                - !Ref "AWS::AccountId"
                - !Ref S3BucketNameSuffix
        - Key: ProjectName
          Value: !Ref ProjectName

  # - - - - - - - - - - - - - - - - -
  S3BucketEcsLogs:
    # - - - - - - - - - - - - - - - - -
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Join
        - '-'
        - - !Ref ProjectName
          - !Ref Stage
          - ecs
          - logs
          - !If
            - UseDefaultAccountId
            - !Ref "AWS::AccountId"
            - !Ref S3BucketNameSuffix
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Suspended
      LifecycleConfiguration:
        Rules:
          - Id: PurgeOutdatedArtifacts
            Status: Enabled
            ExpirationInDays: 30
      Tags:
        - Key: Name
          Value: !Join
            - '-'
            - - !Ref ProjectName
              - !Ref Stage
              - ecs
              - logs
              - !If
                - UseDefaultAccountId
                - !Ref "AWS::AccountId"
                - !Ref S3BucketNameSuffix
        - Key: ProjectName
          Value: !Ref ProjectName

# + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +
Outputs:
# + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +
# - - - - - - - - - - - - - - - - -
  LogGroup:
    Value: !Ref LogGroup
    Export:
      Name: !Join
        - '-'
        - - ECS
          - LogGroup
          - !Ref ProjectName
          - !Ref Stage

# - - - - - - - - - - - - - - - - -
  TaskExecRole:
    Value: !Ref TaskExecRole
    Export:
      Name: !Join
            - '-'
            - - ECS
              - ExecRole
              - !Ref ProjectName
              - !Ref Stage

# - - - - - - - - - - - - - - - - -
  TaskExecRoleArn:
    Value: !GetAtt TaskExecRole.Arn
    Export:
      Name: !Join
            - '-'
            - - ECS
              - ExecRoleArn
              - !Ref ProjectName
              - !Ref Stage

  # - - - - - - - - - - - - - - - - -
  TaskRole:
    Value: !Ref TaskRole
    Export:
      Name: !Join
        - '-'
        - - ECS
          - TaskRole
          - !Ref ProjectName
          - !Ref Stage

  # - - - - - - - - - - - - - - - - -
  TaskRoleArn:
    Value: !GetAtt TaskRole.Arn
    Export:
      Name: !Join
        - '-'
        - - ECS
          - TaskRoleArn
          - !Ref ProjectName
          - !Ref Stage

  S3BucketEcsExtras:
    Value: !Ref S3BucketEcsExtras
    Export:
      Name: !Join
        - '-'
        - - S3Bucket
          - !Ref ProjectName
          - !Ref Stage
          - ecs
          - extras

  S3BucketEcsExtrasArn:
    Value: !GetAtt S3BucketEcsExtras.Arn
    Export:
      Name: !Join
        - '-'
        - - S3BucketArn
          - !Ref ProjectName
          - !Ref Stage
          - ecs
          - extras

  S3BucketEcsLogs:
    Value: !Ref S3BucketEcsLogs
    Export:
      Name: !Join
        - '-'
        - - S3Bucket
          - !Ref ProjectName
          - !Ref Stage
          - ecs
          - logs

  S3BucketEcsLogsArn:
    Value: !GetAtt S3BucketEcsLogs.Arn
    Export:
      Name: !Join
        - '-'
        - - S3BucketArn
          - !Ref ProjectName
          - !Ref Stage
          - ecs
          - logs