AWSTemplateFormatVersion: '2010-09-09'
Description: 'CI ECR.'

Parameters:
  ProjectName:
    Type: String
    Default: bootapps-tmpl
  Stage:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prd
  ApplicationName:
    Type: String
    Default: webapp-example

# + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +
Resources:
# + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +
# - - - - - - - - - - - - - - - - -
  Repository:
# - - - - - - - - - - - - - - - - -
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Join
            - '/'
            - - !Ref ProjectName
              - !Ref Stage
              - !Ref ApplicationName
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep all tagged images and untagged 20 images, expire all others",
                "action": {
                  "type": "expire"
                },
                "selection": {
                  "countType": "imageCountMoreThan",
                  "countNumber": 20,
                  "tagStatus": "untagged"
                }
              }
            ]
          }

#  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Outputs:
#  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# - - - - - - - - - - - - - - - - -
  Repository:
    Value: !Ref Repository
    Export:
      Name: !Join
            - '-'
            - - EcrRepository
              - !Ref ProjectName
              - !Ref Stage
              - !Ref ApplicationName
