version: '3'
services:
  db:
    image: postgres:16.9-alpine
    container_name: postgres16.9-example
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "55432:5432"
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
