AWSTemplateFormatVersion: '2010-09-09'
Description: 'Codebuild.'
Parameters:
  ProjectName:
    Type: String
    Default: bootapps-tmpl

  Stage:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prd

  GithubOrganization:
    Type: String
    Default: value-it

  GithubRepository:
    Type: String
    Default: springboot-apps-template

  ApplicationName:
    Type: String
    Default: webapp-example

# + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +
Mappings:
  # + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +
  spec:
    dev:
      ComputeType: BUILD_GENERAL1_MEDIUM

    prod:
      ComputeType: BUILD_GENERAL1_MEDIUM

    # BUILD_GENERAL1_SMALL  = 2vCPU/RAM3GB
    # BUILD_GENERAL1_MEDIUM = 4vCPU/RAM7GB
    # BUILD_GENERAL1_LARGE  = 8vCPU/RAM15GB

# + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +
Resources:
# + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +
  # - - - - - - - - - - - - - - - - -
  CodeBuild:
  # - - - - - - - - - - - - - - - - -
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      BadgeEnabled: false
      Description: !Sub "build ${ProjectName} application"
      Name: !Join
        - '-'
        - - !Ref ProjectName
          - app-buiild
      ServiceRole:
        Fn::ImportValue:
          !Sub CodebuildRole-${ProjectName}
      Environment:
        Type: LINUX_CONTAINER
        # CodeBuild内でdockerビルドできるようにするために特権付与
        PrivilegedMode: True
        ComputeType: !FindInMap [ spec, !Ref Stage, ComputeType ]

        Image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
        EnvironmentVariables:
          # ======================
          # 環境変数
          # ======================
          - Name: ENV
            Value: !Ref Stage
            Type: PLAINTEXT
          - Name: IMAGE_REPOSITORY_NAME
            Value: !Sub "${ProjectName}/application"
            Type: PLAINTEXT

      Source:
        Type: CODEPIPELINE
        BuildSpec: !Sub "${ApplicationName}/buildspec.yml"

      TimeoutInMinutes: 30

# + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +
Outputs:
# + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +

  # - - - - - - - - - - - - - - - - -
  CodeBuild:
    Value: !Ref CodeBuild
    Export:
      Name: !Join
        - '-'
        - - CodeBuild
          - !Sub ${ProjectName}
