name: Codepipeline Trigger

on:
  push:
    branches:
      - develop
    paths:
      - 'webapp-example/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Trigger AWS CodePipeline
        # v1.0.7
        uses: zulhfreelancer/aws-codepipeline-action@492467f78d67ac2301e55e208326a8e9fbd23284
        with:
          aws-region: 'ap-northeast-1'
          aws-access-key: ${{ secrets.AWS_PIPELINE_ACCESS_KEY }}
          aws-secret-key: ${{ secrets.AWS_PIPELINE_SECRET_KEY }}
          pipeline-name: 'bootapps-tmpl-deploy-pipeline'